name: 'Uncomplicated registry Action'
description: 'Run Uncomplicated registry upload command as part of a GitHub action workflow'
author: 'MichielBijland'

inputs:
  version:
    description: 'uncomplicated registry version'
    default: 'latest'
    required: false

outputs:
  output:
    description: 'Results of running the changie command'

runs:
  using: 'node16'
  main: 'dist/index.js'